"""
Radar theme constants ported from radar_theme.h.
Exact pixel dimensions and colors for faithful reproduction.
"""

# Display dimensions
SIZE = 240
CENTER_X = SIZE // 2
CENTER_Y = SIZE // 2

# Grid geometry
GRID_OUTER_RADIUS = 107

# Cardinal label offsets
CARDINAL_NORTH_OFFSET_Y = -1
CARDINAL_SOUTH_OFFSET_Y = 3

# Scale label gap from outer ring
SCALE_GAP_FROM_OUTER_RING = 6

# Label heights (pixels)
CARDINAL_LABEL_HEIGHT_PX = 14
SCALE_BELOW_CARDINAL_PX = 3

# Ring count
RING_COUNT = 4

# Grid stroke width
GRID_STROKE_HALF_WIDTH = 1.0

# Center dot
CENTER_DOT_RADIUS = 2

# Aircraft symbol dimensions
AIRCRAFT_NOSE_LEN_PX = 8
AIRCRAFT_TAIL_LEN_PX = 3
AIRCRAFT_TAIL_HALF_PX = 4

# Track vector settings
AIRCRAFT_TRACK_HORIZON_SEC = 60.0
AIRCRAFT_SPEED_LINE_MIN_PX = 2
AIRCRAFT_TRACK_REF_OUTER_KM = 13.3
AIRCRAFT_TRACK_LENGTH_SCALE = 1.5 / 5.0
AIRCRAFT_TRACK_LINE_HALF_WIDTH = 1.0

# Runway settings
RUNWAY_LINE_WIDTH_PX = 2.0
RUNWAY_LINE_HALF_WIDTH = RUNWAY_LINE_WIDTH_PX * 0.5
RUNWAY_LABEL_HEIGHT_PX = CARDINAL_LABEL_HEIGHT_PX
RUNWAY_LABEL_GAP_PX = 3

# Aircraft label settings
AIRCRAFT_LABEL_GAP_PX = 1
AIRCRAFT_INSIDE_RING_INSET_PX = AIRCRAFT_NOSE_LEN_PX + AIRCRAFT_TAIL_HALF_PX + 1

# Beyond-ring dots
BEYOND_RING_DOT_RADIUS_PX = 4
BEYOND_RING_SCREEN_MARGIN_PX = 2
AIRCRAFT_TAG_LABEL_HEIGHT_PX = 13

# RGB565 palette targets
BG_R, BG_G, BG_B = 4, 10, 28
GRID_R, GRID_G, GRID_B = 16, 100, 32
AIRCRAFT_R, AIRCRAFT_G, AIRCRAFT_B = 255, 0, 0
TRACK_R, TRACK_G, TRACK_B = 255, 0, 255
TAG_TYPE_R, TAG_TYPE_G, TAG_TYPE_B = 255, 200, 0
TAG_ALT_R, TAG_ALT_G, TAG_ALT_B = 90, 200, 255
TAG_SQUAWK_R, TAG_SQUAWK_G, TAG_SQUAWK_B = 0, 255, 0
RUNWAY_R, RUNWAY_G, RUNWAY_B = 56, 150, 170
RUNWAY_LABEL_R, RUNWAY_LABEL_G, RUNWAY_LABEL_B = 110, 210, 230

# Color cache (will be initialized by display driver)
COLOR_BACKGROUND = None
COLOR_GRID = None
COLOR_LABEL = None
COLOR_CENTER = None
COLOR_AIRCRAFT = None
COLOR_TRACK_VECTOR = None
COLOR_TAG_TYPE = None
COLOR_TAG_ALTITUDE = None
COLOR_TAG_SQUAWK = None
COLOR_RUNWAY = None
COLOR_RUNWAY_LABEL = None
